### ISSUE TITLE
Error when run application after bootstrap for missing dependencies

### ISSUE THREAD

**Issue by IgnacioAbadie** [Wolox/wolmo-bootstrap-react-native#140]
I get the next error when run the application after bootstrap:
![image](https://user-images.githubusercontent.com/24418053/73385557-26bdc300-42ac-11ea-83f9-74e8bff08d33.png)

there is two missing dependencies. Installing these solve the issue.

Missing dependencies are 
```
@react-native-community/masked-view
react-native-safe-area-context
```
Related issue
https://github.com/react-navigation/stack/issues/323

**Comment by sfernandez11** [comment]
Thanks! Solved 😄
