### ISSUE TITLE
Fastlane

### ISSUE THREAD

**Issue by sbalay** [Wolox/wolmo-bootstrap-react-native#2]
Add fastlane tasks to automate ios certificates, profiles and builds handling

**Comment by sbalay** [comment]
check https://github.com/Wolox/w360-react-native/commit/3b9980cbd3381738d25f350303094e3b7b175951 and https://github.com/Wolox/w360-react-native/commit/af7fbe4d1a92ba018cc01110ffcc8a7fe9bf905e

**Comment by mvbattan** [comment]
@sbalay links seems to be down.

**Comment by sbalay** [comment]
those are private
